const SubregionEnumToString = {
  Antarctica: 'Antarctica',
  Australia_and_New_Zealand: 'Australia and New Zealand',
  Caribbean: 'Caribbean',
  Central_America: 'Central America',
  Central_Asia: 'Central Asia',
  Eastern_Africa: 'Eastern Africa',
  Eastern_Asia: 'Eastern Asia',
  Eastern_Europe: 'Eastern Europe',
  Indian_Ocean: 'Indian Ocean',
  Melanesia: 'Melanesia',
  Micronesia: 'Micronesia',
  Middle_Africa: 'Middle Africa',
  Northern_Africa: 'Northern Africa',
  Northern_America: 'Northern America',
  Northern_Europe: 'Northern Europe',
  Polynesia: 'Polynesia',
  South_America: 'South America',
  South_Atlantic_Ocean: 'South Atlantic Ocean',
  South_Eastern_Asia: 'South-Eastern Asia',
  Southern_Africa: 'Southern Africa',
  Southern_Europe: 'Southern Europe',
  Western_Africa: 'Western Africa',
  Western_Asia: 'Western Asia',
  Western_Europe: 'Western Europe',
  Southern_Asia: 'Southern Asia',
};

export { SubregionEnumToString };
